# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-16 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20171216_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantlocation',
            name='time_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
