# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-21 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_auto_20171216_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantlocation',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
